version: '3'
services:
  sta:
    image: 52n/sensorthingsapi
    build:
      context: .
      dockerfile: sensor-things-api-app/Dockerfile
    ports:
      - 8081:8081
      - 1883:1883
      - 8883:8883
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/sta"
      - "MQTT_BROKER_PLAINTCP_ENABLED=true"
      - "MQTT_BROKER_WEBSOCKET_ENABLED=true"
      - "MQTT_BROKER_PERSISTENCE_ENABLED=true"
      - "LOGGING_LEVEL_ROOT=INFO"

  database:
    image: mdillon/postgis
    restart: on-failure
    environment:
      - POSTGRES_DB=sta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis

    # For debug/show purposes!
    ports:
      - 5000:5432
