# Log Bean initiation process
debug: false
trace: false

# General Server Configuration
server:
  port: 8081
  rootUrl: http://115.115.91.50:8081

# Database Configuration
database:
  jpa:
    persistence-location: classpath:META-INF/persistence.xml
spring:
  datasource:
    platform: postgres
    # the db user name
    username: postgres
    # the db user password
    password: softweb
    # here 'sta' is the name of the database
    url: jdbc:postgresql://localhost:5432/sta
    initialization-mode: always
  hikari:
    connection-timeout: 20000
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 300000 
  jpa:
    properties:
      hibernate:
        # the name of the schema in the database
        #default_schema: sta
        hbm2ddl:
          # hbm2ddl values: validate | update | create | create-drop | none
          auto: validate
          ddl-auto: update
        jdbc:
          time_zone: UTC
          # https://hibernate.atlassian.net/browse/HHH-12368
          lob.non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

        # disable driver's feature detection
        # see https://stackoverflow.com/questions/46493500/hibernate-with-c3p0-createclob-is-not-yet-implemented
        temp.use_jdbc_metadata_defaults: false
  jmx:
    enabled: false


# HTTP Configuration
http:
  cors:
    allowOrigin: "*"
    allowMethods: "POST, PUT, GET, OPTIONS, DELETE, PATCH"
    allowHeaders: "Access-Control-Allow-Headers, Content-Type, Authorization, X-Requested-With"
    maxAge: 3600

# MQTT Configuration
mqtt:
  broker:
    plaintcp:
      enabled: true
      port: 1883
    websocket:
      enabled: true
      port: 8883
    persistence:
      enabled: true
      path: "" # Empty for default path (java "user.dir")
      filename: "52N-STA-MQTTBroker.h2"
      autosave_interval: "10"
    
# Logging
logging:
  file: logs/52n-sensorthings-webapp.log
  logging.file.max-history: 10
  level:
    # root: TRACE
    org.apache.coyote.http11.Http11InputBuffer: INFO
    org.n52.sta: INFO
    org.hibernate: INFO
    org.hibernate.type: INFO
    org.hibernate.SQL: INFO
    io.moquette: INFO